"""Generate tools/standalone_night_patch.py from the R13 day package and the current output.

The generated script is stdlib-only and carries the level.SCNE entry-level
delta plus the new buffers, so another machine can turn its local R13 or
earlier night package into a copy of the current output without the repo.

Usage: python -X utf8 tools/make_standalone_patch.py [path to R13 arena_700_int.iff]
Default R13 path is the Git LFS object cache of this checkout.
"""
from pathlib import Path
import base64
import hashlib
import json
import sys
import zipfile
import zlib
from iff_codec import load_scne

ROOT = Path(__file__).resolve().parents[1]
R13_SHA256 = '9e9cd0f73b1c6c2baf6d9f45cb472ac110282e7d161c20ce9d373fd968532622'
EARLIER = {
    R13_SHA256: 'R13 day',
    '12efd7a280d5a3521e72434534cd16a2b1948777a58464ad66f06f2e9a3d531f': 'R13+N1 night',
    '92e0c75b9b7af82387bbb9c8f05534f35aa450c27cf6f22753ec9446761e804d': 'R13+N2 night',
    '8f8a4d119242a1098651f04fdcc6344c5a6a086288ed55fb206310d6c483b0cb': 'R13+N3 night',
}
SECTIONS = ('Light', 'Material', 'Model', 'Object')

TEMPLATE = r'''"""Standalone {revision} night patch for an existing arena_700_int.iff (Python 3.8+, stdlib only).

Usage:  python standalone_night_patch.py "D:\\path\\to\\arena_700_int.iff"

Generated by tools/make_standalone_patch.py. Accepts only the R13 day package or
an earlier night test ({accepted}), rewrites level.SCNE, appends the new
buffers, copies every other ZIP record byte-for-byte, verifies the content, then
keeps the first pre-night file as .before-night.bak.
"""
import base64
import copy
import hashlib
import json
import os
import sys
import zipfile
import zlib

REVISION = {revision!r}
KNOWN_INPUTS = {known!r}
EXPECTED_SCNE_SHA256 = {scne_sha!r}
PAYLOAD = {payload!r}


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for block in iter(lambda: f.read(8 * 1024 * 1024), b''):
            h.update(block)
    return h.hexdigest()


def load_scne(raw):
    def unique(pairs):
        out = {{}}
        for k, v in pairs:
            if k in out:
                raise ValueError('Duplicate SCNE key: ' + k)
            out[k] = v
        return out
    return json.loads('{{' + raw.decode('utf-8-sig') + '}}', object_pairs_hook=unique)


def dump_scne(doc):
    return (json.dumps(doc, ensure_ascii=True, indent='\t')[1:-1].strip() + '\n').encode('utf8')


def copy_record(source, target, info, end):
    cloned = copy.copy(info)
    target._writecheck(cloned)
    target._didModify = True
    target.fp.seek(target.start_dir)
    cloned.header_offset = target.fp.tell()
    source.fp.seek(info.header_offset)
    remaining = end - info.header_offset
    while remaining:
        block = source.fp.read(min(8 * 1024 * 1024, remaining))
        if not block:
            raise ValueError('Unexpected archive end')
        target.fp.write(block)
        remaining -= len(block)
    target.start_dir = target.fp.tell()
    target.filelist.append(cloned)
    target.NameToInfo[cloned.filename] = cloned


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    path = os.path.abspath(sys.argv[1])
    print('Checking input identity (about a minute for 1.7 GB)...', flush=True)
    digest = sha256_file(path)
    if digest not in KNOWN_INPUTS:
        sys.exit('Refusing: input is not a known R13 / night test package (sha256 %s)' % digest)
    print('Input is', KNOWN_INPUTS[digest], '-> patching to', REVISION, flush=True)
    payload = json.loads(zlib.decompress(base64.b64decode(PAYLOAD)))
    added = [(name, base64.b64decode(data)) for name, data in payload['members']]
    pending = path + '.pending'
    with zipfile.ZipFile(path) as src:
        doc = load_scne(src.read('level.SCNE'))
        level = doc['level']
        for section, entries in payload['set'].items():
            level[section].update(entries)
        new_scne = dump_scne(doc)
        if hashlib.sha256(new_scne).hexdigest() != EXPECTED_SCNE_SHA256:
            sys.exit('Refusing: patched level.SCNE does not match the expected ' + REVISION + ' content')
        ordered = sorted(src.infolist(), key=lambda i: i.header_offset)
        ends = {{i.filename: (ordered[j + 1].header_offset if j + 1 < len(ordered) else src.start_dir)
                for j, i in enumerate(ordered)}}
        print('Writing patched package...', flush=True)
        with zipfile.ZipFile(pending, 'w', compression=zipfile.ZIP_DEFLATED, allowZip64=False) as out:
            out.comment = src.comment
            for info in src.infolist():
                if info.filename == 'level.SCNE':
                    item = copy.copy(info)
                    item.compress_type = zipfile.ZIP_DEFLATED
                    out.writestr(item, new_scne, compress_type=zipfile.ZIP_DEFLATED, compresslevel=6)
                else:
                    copy_record(src, out, info, ends[info.filename])
            for name, data in added:
                info = zipfile.ZipInfo(name, (2014, 1, 1, 17, 0, 0))
                info.compress_type = zipfile.ZIP_DEFLATED
                out.writestr(info, data, compress_type=zipfile.ZIP_DEFLATED, compresslevel=6)
        print('Verifying...', flush=True)
        with zipfile.ZipFile(pending) as final:
            assert final.namelist() == src.namelist() + [n for n, _ in added]
            assert final.testzip() is None
            assert hashlib.sha256(final.read('level.SCNE')).hexdigest() == EXPECTED_SCNE_SHA256
            for name, data in added:
                assert final.read(name) == data
            for old in src.infolist():
                new = final.getinfo(old.filename)
                if old.filename != 'level.SCNE':
                    assert (old.CRC, old.file_size, old.compress_size) == (new.CRC, new.file_size, new.compress_size)
    backup = path + '.before-night.bak'
    if os.path.exists(backup):
        # Keep the first (pre-night) backup; the replaced file is an older night test.
        os.replace(pending, path)
    else:
        os.replace(path, backup)
        os.replace(pending, path)
    print('Done. Patched to', REVISION + ':', path)
    print('Pre-night original kept as:', backup, '(move it out of levels; rename it back to undo)')


if __name__ == '__main__':
    main()
'''


def main():
    r13 = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT.parents[1] / '.git/lfs/objects' / R13_SHA256[:2] / R13_SHA256[2:4] / R13_SHA256
    report = json.loads((ROOT / 'validation/iff-current.json').read_text(encoding='utf8'))
    with zipfile.ZipFile(r13) as day, zipfile.ZipFile(ROOT / 'output/arena_700_int.iff') as current:
        before = load_scne(day.read('level.SCNE'))['level']
        raw = current.read('level.SCNE')
        after = load_scne(raw)['level']
        assert set(before) == set(after)
        for key in before:
            if key not in SECTIONS:
                assert before[key] == after[key], key
        delta = {}
        for section in SECTIONS:
            assert set(before[section]) <= set(after[section]), section
            changed = {k: v for k, v in after[section].items() if before[section].get(k) != v}
            if changed:
                delta[section] = changed
        old_names = day.namelist()
        names = current.namelist()
        assert names[:len(old_names)] == old_names
        members = [(n, base64.b64encode(current.read(n)).decode()) for n in names[len(old_names):]]
    payload = base64.b64encode(zlib.compress(json.dumps({'set': delta, 'members': members}).encode(), 9)).decode()
    revision = report['revision']
    known = {k: v for k, v in EARLIER.items() if k != report['output_sha256']}
    text = TEMPLATE.format(revision=revision, accepted=', '.join(v for v in known.values() if v != 'R13 day'),
                           known=known, scne_sha=hashlib.sha256(raw).hexdigest(), payload=payload)
    out = ROOT / 'tools/standalone_night_patch.py'
    out.write_text(text, encoding='utf8')
    print(json.dumps({'script': str(out), 'bytes': len(text.encode()), 'revision': revision,
                      'entries_set': {k: len(v) for k, v in delta.items()}, 'new_members': len(members)}))


if __name__ == '__main__':
    main()
