"""Generate tools/standalone_night_patch.py from the R13 day package and the current output.

The generated script is stdlib-only and carries the level.SCNE entry-level
delta plus the new buffers, so another machine can turn its local R13 or
earlier night package into a copy of the current output without the repo.

Usage: python -X utf8 tools/make_standalone_patch.py [--since REVISION] [path to R13 arena_700_int.iff]
Default R13 path is the Git LFS object cache of this checkout.

Every run records the generated revision (its level.SCNE and appended member
names) in build/releases/. With --since REVISION the script is incremental: it
carries only the entries and buffers that changed since that recorded release
and accepts only that release as input (the user asked for small per-version
patches instead of the full R13 -> current payload).
"""
from pathlib import Path
import base64
import hashlib
import json
import os
import sys
import zipfile
import zlib
from iff_codec import load_scne

ROOT = Path(__file__).resolve().parents[1]
R13_SHA256 = '9e9cd0f73b1c6c2baf6d9f45cb472ac110282e7d161c20ce9d373fd968532622'
# Inputs are recognised by level.SCNE content: ZIP metadata of appended members
# (create_system) differs between Windows and macOS Python, file hashes do not match.
EARLIER = {
    '7ca3aa302d3faa7d8d316ab045e2512ddf765f42b732f3ca911a0c5fb517d0ec': 'R13 day',
    '7083d5bf3ba8539efea801e89f71e52f4f51ee9dbeb1d94c0ad1dde05605aff9': 'R13+N1 night',
    '0447d8a261b4ce6e01bc6a8e8026e904d641355de48a74ccd83cdaba8e661d44': 'R13+N2 night',
    '006732d281a524a7d24727b48b7d08fda3219e8108773a77df63f1af60cf680b': 'R13+N3 night',
    'b8c57adb561f45bf026941c78605b47f4eda0fc1e48fc2a2d35f9d371980c729': 'R13+N3+N4 night scene',
    'fa40f55db0141e95a862d7b3720a1c99626084d7250ee7f8943011ff4d43bf0d': 'R13+N3+N6 night scene',
    '42c9914321c43ace70fc8645a8e9c936a79dd2249a2fa45bb2158a2fff2537df': 'LDIAG1 lighting diagnostic',
    '6e8459ea0ff7b2a70418b42dece3653e8f3eb1d7ba014047c5ded0cc62e5b795': 'R13+N3+N4 light diagnostic',
    'e075cbefb34cae6d050a32101ac628b017f47b1d92adc9bd4f9aa913fd90d680': 'R13+N3.5+N16 night scene',
}
SECTIONS = ('Light', 'Material', 'Model', 'Object', 'Texture')
# Earlier night-scene test entries the patch removes before applying this output.
DELETE_PREFIXES = ['zgc_n4:', 'zgc_n5:', 'zgc_n6:', 'zgc_probe_emit:', 'zgc_diag_receiver:', 'zgc_n7:', 'zgc_n8:', 'zgc_n9:', 'zgc_n10:', 'zgc_n11:', 'zgc_n12:', 'zgc_n13:', 'zgc_n14:', 'zgc_n15:', 'zgc_n16:']

TEMPLATE = r'''"""Standalone {revision} night patch for an existing arena_700_int.iff (Python 3.8+, stdlib only).

Usage:  python standalone_night_patch.py "D:\\path\\to\\arena_700_int.iff"

Generated by tools/make_standalone_patch.py. {accepts_text} Rewrites level.SCNE,
appends the new buffers, copies every other ZIP record byte-for-byte, verifies
the content, then keeps the first pre-night file as .before-night.bak.
"""
import base64
import copy
import hashlib
import json
import os
import sys
import zipfile
import zlib

REVISION = {revision!r}
KNOWN_INPUTS = {known!r}
EXPECTED_SCNE_SHA256 = {scne_sha!r}
BASE_COUNT = {base_count!r}
REQUIRED_INPUT = {required!r}
REPLACED_SHA256 = {replaced_sha!r}   # other whole members this version replaces (e.g. baskets.SCNE)   # (revision, level.SCNE sha256) for incremental patches, else None
BASE_NAMES_SHA256 = {base_names!r}
PAYLOAD = {payload!r}


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for block in iter(lambda: f.read(8 * 1024 * 1024), b''):
            h.update(block)
    return h.hexdigest()


def load_scne(raw):
    def unique(pairs):
        out = {{}}
        for k, v in pairs:
            if k in out:
                raise ValueError('Duplicate SCNE key: ' + k)
            out[k] = v
        return out
    return json.loads('{{' + raw.decode('utf-8-sig') + '}}', object_pairs_hook=unique)


def dump_scne(doc):
    return (json.dumps(doc, ensure_ascii=True, indent='\t')[1:-1].strip() + '\n').encode('utf8')


def copy_record(source, target, info, end):
    cloned = copy.copy(info)
    target._writecheck(cloned)
    target._didModify = True
    target.fp.seek(target.start_dir)
    cloned.header_offset = target.fp.tell()
    source.fp.seek(info.header_offset)
    remaining = end - info.header_offset
    while remaining:
        block = source.fp.read(min(8 * 1024 * 1024, remaining))
        if not block:
            raise ValueError('Unexpected archive end')
        target.fp.write(block)
        remaining -= len(block)
    target.start_dir = target.fp.tell()
    target.filelist.append(cloned)
    target.NameToInfo[cloned.filename] = cloned


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    path = os.path.abspath(sys.argv[1])
    with zipfile.ZipFile(path) as probe:
        digest = hashlib.sha256(probe.read('level.SCNE')).hexdigest()
        base_ok = len(probe.namelist()) >= BASE_COUNT and hashlib.sha256(
            '\n'.join(probe.namelist()[:BASE_COUNT]).encode()).hexdigest() == BASE_NAMES_SHA256
    if digest == EXPECTED_SCNE_SHA256:
        sys.exit('Already ' + REVISION + '; nothing to do')
    if not base_ok:
        sys.exit('Refusing: input is not built on the R13 package')
    if REQUIRED_INPUT and digest != REQUIRED_INPUT[1]:
        sys.exit('Refusing: this incremental patch only upgrades ' + REQUIRED_INPUT[0] +
                 ' -> ' + REVISION + '. Apply the ' + REQUIRED_INPUT[0] + ' patch first.')
    # Any earlier night test is accepted only if the patched scene matches exactly (checked below).
    print('Input is', KNOWN_INPUTS.get(digest, 'an earlier night test'), '-> patching to', REVISION, flush=True)
    payload = json.loads(zlib.decompress(base64.b64decode(PAYLOAD)))
    pending = path + '.pending'
    with zipfile.ZipFile(path) as src:
        final_appended = set(payload.get('final_members') or [n for n, _ in payload['members']])
        drop = {{n for n in src.namelist()[BASE_COUNT:] if n not in final_appended}}
        added = []
        for name, data in payload['members']:
            data = base64.b64decode(data)
            if name in src.NameToInfo:
                # Content-addressed buffer already present from an earlier test package.
                assert src.read(name) == data, name
            else:
                added.append((name, data))
        doc = load_scne(src.read('level.SCNE'))
        level = doc['level']
        for section in list(level):
            if isinstance(level[section], dict):
                for key in [k for k in level[section] if k.startswith(tuple(payload['delete_prefixes']))]:
                    del level[section][key]
        for section, keys in payload.get('delete_keys', {{}}).items():
            for key in keys:
                del level[section][key]
        for section, entries in payload['set'].items():
            level[section].update(entries)
        for section, keys in payload.get('order', {{}}).items():
            # incremental patches: new entries sit between existing ones in the build
            assert set(keys) == set(level[section]), section
            level[section] = {{k: level[section][k] for k in keys}}
        new_scne = dump_scne(doc)
        replace = {{n: base64.b64decode(d) for n, d in payload.get('replace', {{}}).items()}}
        for name, sha in REPLACED_SHA256.items():
            data = replace.get(name, src.read(name))
            if hashlib.sha256(data).hexdigest() != sha:
                sys.exit('Refusing: ' + name + ' of the input is not the expected one')
            replace[name] = data
        if hashlib.sha256(new_scne).hexdigest() != EXPECTED_SCNE_SHA256:
            sys.exit('Refusing: input is not a recognised R13 / night test package (patched level.SCNE differs)')
        ordered = sorted(src.infolist(), key=lambda i: i.header_offset)
        ends = {{i.filename: (ordered[j + 1].header_offset if j + 1 < len(ordered) else src.start_dir)
                for j, i in enumerate(ordered)}}
        print('Writing patched package...', flush=True)
        with zipfile.ZipFile(pending, 'w', compression=zipfile.ZIP_DEFLATED, allowZip64=False) as out:
            out.comment = src.comment
            for info in src.infolist():
                if info.filename in drop:
                    continue
                if info.filename in replace:
                    item = copy.copy(info)
                    item.compress_type = zipfile.ZIP_DEFLATED
                    out.writestr(item, replace[info.filename], compress_type=zipfile.ZIP_DEFLATED, compresslevel=6)
                elif info.filename == 'level.SCNE':
                    item = copy.copy(info)
                    item.compress_type = zipfile.ZIP_DEFLATED
                    out.writestr(item, new_scne, compress_type=zipfile.ZIP_DEFLATED, compresslevel=6)
                else:
                    copy_record(src, out, info, ends[info.filename])
            for name, data in added:
                info = zipfile.ZipInfo(name, (2014, 1, 1, 17, 0, 0))
                info.create_system = 0
                info.compress_type = zipfile.ZIP_DEFLATED
                out.writestr(info, data, compress_type=zipfile.ZIP_DEFLATED, compresslevel=6)
        print('Verifying...', flush=True)
        with zipfile.ZipFile(pending) as final:
            assert final.namelist() == [n for n in src.namelist() if n not in drop] + [n for n, _ in added]
            assert final.testzip() is None
            assert hashlib.sha256(final.read('level.SCNE')).hexdigest() == EXPECTED_SCNE_SHA256
            for name, sha in REPLACED_SHA256.items():
                assert hashlib.sha256(final.read(name)).hexdigest() == sha
            for name, data in added:
                assert final.read(name) == data
            for old in src.infolist():
                if old.filename in drop:
                    continue
                new = final.getinfo(old.filename)
                if old.filename != 'level.SCNE' and old.filename not in replace:
                    assert (old.CRC, old.file_size, old.compress_size) == (new.CRC, new.file_size, new.compress_size)
    backup = path + '.before-night.bak'
    if os.path.exists(backup):
        # Keep the first (pre-night) backup; the replaced file is an older night test.
        os.replace(pending, path)
    else:
        os.replace(path, backup)
        os.replace(pending, path)
    print('Done. Patched to', REVISION + ':', path)
    print('Pre-night original kept as:', backup, '(move it out of levels; rename it back to undo)')


if __name__ == '__main__':
    main()
'''


RELEASES = ROOT / 'build' / 'releases'


def main():
    args = sys.argv[1:]
    since = None
    if args[:1] == ['--since']:
        since, args = args[1], args[2:]
    r13 = Path(args[0]) if args else ROOT.parents[1] / '.git/lfs/objects' / R13_SHA256[:2] / R13_SHA256[2:4] / R13_SHA256
    report = json.loads((ROOT / 'validation/iff-current.json').read_text(encoding='utf8'))
    with zipfile.ZipFile(r13) as day, zipfile.ZipFile(ROOT / 'output/arena_700_int.iff') as current:
        raw = current.read('level.SCNE')
        after = load_scne(raw)['level']
        old_names = day.namelist()
        names = current.namelist()
        assert names[:len(old_names)] == old_names
        appended = names[len(old_names):]
        if since:
            prev_raw = (RELEASES / f'{since}.SCNE').read_bytes()
            before = load_scne(prev_raw)['level']
            prev_members = set(json.loads((RELEASES / f'{since}.json').read_text(encoding='utf8'))['members'])
        else:
            before = load_scne(day.read('level.SCNE'))['level']
            prev_members = set()
        assert set(before) == set(after)
        for key in before:
            if key not in SECTIONS:
                assert before[key] == after[key], key
        delta, deleted = {}, {}
        for section in SECTIONS:
            if not since:
                assert set(before[section]) <= set(after[section]), section
                assert not any(k.startswith(tuple(DELETE_PREFIXES[:-1])) for k in after[section]), section
            changed = {k: v for k, v in after[section].items() if before[section].get(k) != v}
            if changed:
                delta[section] = changed
            gone = sorted(set(before[section]) - set(after[section]))
            if gone:
                deleted[section] = gone
        members = [(n, base64.b64encode(current.read(n)).decode()) for n in appended if n not in prev_members]
        # whole-member replacements (only baskets.SCNE so far), relative to R13 or the previous release
        replaced_sha, replace = {}, {}
        for name in ('baskets.SCNE',):
            data = current.read(name)
            sha = hashlib.sha256(data).hexdigest()
            if sha != hashlib.sha256(day.read(name)).hexdigest():
                replaced_sha[name] = sha
                prev_sha = (json.loads((RELEASES / f'{since}.json').read_text(encoding='utf8')).get('replaced', {}).get(name)
                            if since else None)
                if sha != prev_sha:
                    replace[name] = base64.b64encode(data).decode()
    order = {s: list(after[s]) for s in SECTIONS
             if since and list(after[s]) != [k for k in before[s] if k in after[s]] + [k for k in after[s] if k not in before[s]]}
    body = {'set': delta, 'members': members, 'final_members': appended, 'replace': replace, 'order': order,
            'delete_prefixes': [] if since else DELETE_PREFIXES, 'delete_keys': deleted}
    payload = base64.b64encode(zlib.compress(json.dumps(body).encode(), 9)).decode()
    revision = report['revision'] + ('-light-diagnostic' if os.environ.get('ZGC_LIGHT_DIAGNOSTIC') == '1' else '')
    if since:
        prev_sha = hashlib.sha256(prev_raw).hexdigest()
        required = (since, prev_sha)
        accepts = f'Incremental: accepts only {since} (level.SCNE {prev_sha[:12]}).'
        known = {prev_sha: since}
    else:
        required = None
        known = {k: v for k, v in EARLIER.items() if k != hashlib.sha256(raw).hexdigest()}
        accepts = 'Accepts the R13 day package or an earlier night test (' + ', '.join(v for v in known.values() if v != 'R13 day') + ').'
    text = TEMPLATE.format(revision=revision, accepts_text=accepts, required=required, replaced_sha=replaced_sha,
                           known=known, scne_sha=hashlib.sha256(raw).hexdigest(), payload=payload,
                           base_count=len(old_names), base_names=hashlib.sha256('\n'.join(old_names).encode()).hexdigest())
    out = ROOT / 'tools/standalone_night_patch.py'
    out.write_text(text, encoding='utf8')
    RELEASES.mkdir(parents=True, exist_ok=True)
    tag = report['revision'].split('+')[-1]
    (RELEASES / f'{tag}.SCNE').write_bytes(raw)
    (RELEASES / f'{tag}.json').write_text(json.dumps({'revision': revision, 'scne_sha256': hashlib.sha256(raw).hexdigest(),
                                                      'members': appended, 'since': since,
                                                      'replaced': replaced_sha}), encoding='utf8')
    print(json.dumps({'script': str(out), 'bytes': len(text.encode()), 'revision': revision, 'since': since,
                      'entries_set': {k: len(v) for k, v in delta.items()}, 'entries_deleted': {k: len(v) for k, v in deleted.items()},
                      'new_members': len(members), 'replaced': list(replace), 'release_recorded': tag}))


if __name__ == '__main__':
    main()
